namespace backend_gym_webapp.Models
{
    /// <summary>
    /// GymClass - Represents a fitness class that users can enroll in
    /// 
    /// This class is mapped to the "GymClasses" table in SQL Server
    /// Examples: Yoga, CrossFit, Swimming, Pilates, etc.
    /// 
    /// How it's used:
    /// 1. Entity Framework uses this class to create/read/update the database table
    /// 2. When you create a new class, it gets stored here
    /// 3. The controller receives requests and converts them to this class
    /// 4. The service performs business logic on this data
    /// </summary>
    public class GymClass
    {
        // ===== PRIMARY KEY =====
        /// <summary>
        /// Id - Unique identifier for each gym class
        /// AUTO-GENERATED by the database (don't set this in API requests)
        /// Example: 1, 2, 3, etc.
        /// </summary>
        public int Id { get; set; }

        // ===== BASIC INFORMATION =====
        /// <summary>
        /// Name - The name of the gym class
        /// REQUIRED field (cannot be empty)
        /// MaxLength: 100 characters
        /// Examples: "Morning Yoga", "CrossFit 101", "Pilates Class"
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Description - What this class is about
        /// OPTIONAL field (can be null)
        /// MaxLength: 500 characters
        /// Example: "A relaxing yoga session for all levels"
        /// </summary>
        public string? Description { get; set; }

        /// <summary>
        /// InstructorName - Who teaches this class
        /// REQUIRED field
        /// Example: "John Doe", "Maria Garcia"
        /// </summary>
        public string InstructorName { get; set; } = string.Empty;

        // ===== CAPACITY INFORMATION =====
        /// <summary>
        /// MaxCapacity - Maximum number of participants allowed
        /// REQUIRED field
        /// Must be greater than 0
        /// Example: 20, 30, 50 (maximum number of people in the class)
        /// </summary>
        public int MaxCapacity { get; set; }

        /// <summary>
        /// EnrolledCount - Current number of people enrolled
        /// AUTO-MANAGED by the system (don't set in requests)
        /// Default: 0 (starts at zero when class is created)
        /// This helps determine if class has available spots
        /// </summary>
        public int EnrolledCount { get; set; } = 0;

        // ===== CLASS SCHEDULE & DETAILS =====
        /// <summary>
        /// Schedule - When the class happens
        /// REQUIRED field
        /// Example: "Monday 9:00 AM", "Wednesday 6:30 PM"
        /// Could be formatted as date/time or text
        /// </summary>
        public string Schedule { get; set; } = string.Empty;

        /// <summary>
        /// DifficultyLevel - How hard is this class?
        /// REQUIRED field
        /// Possible values: "Beginner", "Intermediate", "Advanced"
        /// Default: "Beginner"
        /// Helps users find classes at their skill level
        /// </summary>
        public string DifficultyLevel { get; set; } = "Beginner";

        /// <summary>
        /// DurationMinutes - How long the class lasts in minutes
        /// REQUIRED field
        /// Example: 30, 45, 60, 90 (in minutes)
        /// Helps users plan their schedule
        /// </summary>
        public int DurationMinutes { get; set; }

        // ===== PRICING =====
        /// <summary>
        /// Price - Cost per class in dollars
        /// REQUIRED field
        /// Example: 15.99, 20.50, 12.00
        /// Stored as decimal for accurate money calculations
        /// </summary>
        public decimal Price { get; set; }

        // ===== TIMESTAMPS =====
        /// <summary>
        /// CreatedAt - When this class record was created in the database
        /// AUTO-MANAGED by the service (don't set in requests)
        /// Set to UTC time using DateTime.UtcNow
        /// Used for auditing and tracking
        /// Example: "2026-04-05T21:30:00Z"
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// UpdatedAt - When this class record was last modified
        /// AUTO-MANAGED by the service (updated on every change)
        /// Set to UTC time using DateTime.UtcNow
        /// Helps track when class information was last changed
        /// </summary>
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

        // ===== STATUS =====
        /// <summary>
        /// IsActive - Whether this class is currently active/available
        /// Default: true (class is active when created)
        /// Admins can set to false to hide/disable a class
        /// Inactive classes won't show up in "available" listings
        /// </summary>
        public bool IsActive { get; set; } = true;
    }
}
